[DO NOT MERGE] Add page about lightning quacks
compsci-adl/compsci-adl.github.io pull request #7
Opened 2017-04-27 08:56 UTC by katiewalker

Adds a page with information about Lightning Quacks, including a link to register.

Just used a Google form for registration, don't have time to deal with Firebase.

Don't merge yet. We'll fill in the space on the LHS with a graphic, once Rachel's friend is done.

2017-04-27 08:57 UTC, ZacharyForman commented
Lgtm merge at will

On 27 Apr. 2017 18:26, "Katie Walker" <notifications@github.com> wrote:

> Adds a page with information about Lightning Quacks, including a link to
> register.
>
> Just used a Google form for registration, don't have time to deal with
> Firebase.
>
> Don't merge yet. We'll fill in the space on the LHS with a graphic, once
> Rachel's friend is done.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/compsci-adl/compsci-adl.github.io/pull/7
> Commit Summary
>
>    - Add page about lightning quacks
>
> File Changes
>
>    - *M* css/styles.css
>    <https://github.com/compsci-adl/compsci-adl.github.io/pull/7/files#diff-0>
>    (8)
>    - *A* lightning_quacks.html
>    <https://github.com/compsci-adl/compsci-adl.github.io/pull/7/files#diff-1>
>    (210)
>
> Patch Links:
>
>    - https://github.com/compsci-adl/compsci-adl.github.io/pull/7.patch
>    - https://github.com/compsci-adl/compsci-adl.github.io/pull/7.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/compsci-adl/compsci-adl.github.io/pull/7>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AD9UC8GkQ5cPDe9k-hH535ahw6kSyfLGks5r0Fg7gaJpZM4NJ7WV>
> .
>

2017-04-27 09:13 UTC, katiewalker commented
> Lgtm merge at will

Pls.

2017-05-01 09:36 UTC, katiewalker commented
@JakeLane If this is all good, we can publish tonight.

2017-05-01 10:13 UTC, JakeLane requested changes
Just a couple of copy paste artefacts, I'll fix em

2017-05-01 10:13 UTC, JakeLane commented on lightning_quacks.html
> +    <link rel="canonical" href="https://csclub.org.au/about" />
`<link rel="canonical" href="https://csclub.org.au/lightning_quacks" />`

2017-05-01 10:13 UTC, JakeLane commented on lightning_quacks.html
> +        <li class="active"><a href="/about"><i class="material-icons">info</i>About</a></li>
`<li><a href="/about"><i class="material-icons">info</i>About</a></li>`

2017-05-01 10:16 UTC, JakeLane approved these changes

2017-05-01 10:18 UTC, merged